"""empty message

Revision ID: 03b3bed65895
Revises: 2d2c218b9bc7
Create Date: 2023-10-14 23:04:59.581104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b3bed65895'
down_revision = '2d2c218b9bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('relay_group_relay_association',
    sa.Column('relay_group_id', sa.Integer(), nullable=True),
    sa.Column('relay_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['relay_group_id'], ['relay_group.id'], ),
    sa.ForeignKeyConstraint(['relay_id'], ['relay.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relay_group_relay_association')
    op.drop_table('relay_group')
    # ### end Alembic commands ###
