"""Added group is_on

Revision ID: 2129adbf3e0e
Revises: eb91d72750cf
Create Date: 2023-10-02 22:49:30.784818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2129adbf3e0e'
down_revision = 'eb91d72750cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('is_on', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group', 'is_on')
    # ### end Alembic commands ###
