"""empty message

Revision ID: 3f1022c736c4
Revises: c341767e1d47
Create Date: 2023-11-06 22:39:03.874520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1022c736c4'
down_revision = 'c341767e1d47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay_relay_group_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relay_id', sa.Integer(), nullable=False),
    sa.Column('relay_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['relay_group_id'], ['relay_group.id'], ),
    sa.ForeignKeyConstraint(['relay_id'], ['relay.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relay_relay_group_association')
    # ### end Alembic commands ###
