"""empty message

Revision ID: 47704d1d7fa3
Revises: 3f1022c736c4
Create Date: 2023-11-06 23:04:53.135500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47704d1d7fa3'
down_revision = '3f1022c736c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay_relay_group_association', sa.Column('is_on', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relay_relay_group_association', 'is_on')
    # ### end Alembic commands ###
