"""empty message

Revision ID: 600eb0dc7085
Revises: 47704d1d7fa3
Create Date: 2023-11-07 11:43:10.998290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600eb0dc7085'
down_revision = '47704d1d7fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'device_type')
    # ### end Alembic commands ###
