"""empty message

Revision ID: c38f3379590f
Revises: 2129adbf3e0e
Create Date: 2023-10-11 10:34:39.302409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38f3379590f'
down_revision = '2129adbf3e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relay_number', sa.Integer(), nullable=False),
    sa.Column('is_on', sa.Boolean(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relay')
    # ### end Alembic commands ###
