"""Added extra fields

Revision ID: eb91d72750cf
Revises: 3cc640a8615e
Create Date: 2023-10-02 21:33:22.039123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb91d72750cf'
down_revision = '3cc640a8615e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('extra', sa.JSON(), nullable=True))
    op.add_column('device', sa.Column('is_on', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'is_on')
    op.drop_column('device', 'extra')
    # ### end Alembic commands ###
