"""empty message

Revision ID: eeaa00bb6c1a
Revises: 3cc640a8615e
Create Date: 2023-09-30 10:03:46.970756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeaa00bb6c1a'
down_revision = '3cc640a8615e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name')
    )
    op.create_table('group_device_association',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], )
    )
    op.alter_column('device', 'device_ip',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('device', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'device_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('device', 'device_ip',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_table('group_device_association')
    op.drop_table('group')
    # ### end Alembic commands ###
